version: '3.8'
services:
  postgres:
    container_name: cts_postgres
    image: postgres:16.4
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - postgres_data:/data/postgres
      - ./backend/tmp:/tmp
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - common

  node:
    container_name: cts_node
    build:
      context: ./backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks: 
      - common

  nginx:
    container_name: cts_nginx
    image: nginx
    restart: unless-stopped
    volumes:
      - ./frontend:/etc/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${PORT}:80
    depends_on:
      - node
    networks:
      - common

networks:
  common:
    driver: bridge

volumes:
  postgres_data:
