[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[[services]]
internal_port = 3000
protocol = "http"

[mount]
source = "."
destination = "/app"

[env]
PORT = "3000"
NODE_ENV = "production"
