[project]
name = "ctsb_railway"

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node main.js"

[mount]
source = "."
destination = "/app"

[[services]]
name = "api"
internal_port = "3000"
auto_deploy = true

[nixpacks]
start = "node main.js"
