[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
startCommand = "node main.js"

[mount]
source = "."
destination = "/app"

[[services]]
internal_port = 3000
protocol = "http"
auto_deploy = true

[env]
PORT = "3000"
NODE_ENV = "production"
