[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'nginx -g \"daemon off;\"'"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 10
