[project]
name = "ctsf_railway"

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 10
deploymentType = "image"
startCommand = "nginx -g 'daemon off;'"

[[services]]
name = "web"
internal_port = "80"
auto_deploy = true
