export default {
  data: {
    stargazingPagi: {
      edges: [
        {
          stargazing_title: "台東：富源景觀平台",
          stargazing_latitude: 22.828574143383403,
          stargazing_longitude: 121.15307085653819,
          stargazing_image: "/img/mark-0013.jpg",
          stargazing_description:
            "富源景觀平台視野遼闊，可以360度觀景，一邊能眺望都蘭山與綠島，而另一邊則可以看見卑南溪、小黃山、利吉惡地等獨特地理景觀，把東海岸景緻盡收眼底。開闊的視野是觀星的絕佳景點。",
          stargazing_address: "臺東縣卑南鄉富源197縣道56公里處",
          stargazing_link: null,
          stargazing_lid: "1650321470",
          published: true,
          __typename: "Stargazing",
        },
        {
          stargazing_title: "台東：金針山湛藍若洗觀景平台",
          stargazing_latitude: 22.626562086369855,
          stargazing_longitude: 120.97615874768186,
          stargazing_image: "/img/mark-0012.jpg",
          stargazing_description:
            "位於太麻里的金針山是著名的賞花勝地，四季造訪皆能觀賞到滿山遍野不同的花朵盛開美景。除了白天可以賞花看海景外，夜晚也可欣賞星空夜景與月光海色，美不勝收的景色一生一定要去一次。",
          stargazing_address: "台東縣太麻里鄉大王村",
          stargazing_link: "https://goo.gl/maps/AHapEU2vd3EKi2Xk6",
          stargazing_lid: "1650321469",
          published: true,
          __typename: "Stargazing",
        },
        {
          stargazing_title: "台東：鹿野高台高眺亭",
          stargazing_latitude: 22.9173827688225,
          stargazing_longitude: 121.12273028810145,
          stargazing_image: "/img/mark-0011.jpg",
          stargazing_description:
            "鹿野高台為於花東縱谷南段，而鹿野高台也是熱氣球的舉辦的，吸引各地旅客前往朝聖。也因為地勢高，可以俯瞰鹿野溪與卑南溪的匯流口，視野相當開闊，幾乎無光害，是絕佳的觀星地點。",
          stargazing_address: "台東縣鹿野鄉高台路42巷84號",
          stargazing_link: "https://goo.gl/maps/hMRm35kSmvkG5R6Y8",
          stargazing_lid: "1650321468",
          published: true,
          __typename: "Stargazing",
        },
        {
          stargazing_title: "台東：都蘭觀海公園",
          stargazing_latitude: 22.8729189338634,
          stargazing_longitude: 121.23487143597846,
          stargazing_image: "/img/mark-0010.jpg",
          stargazing_description:
            "都蘭觀海公園位於臺11線旁，園區內有兩條對外道路，可區分通道管控車輛通行，而且園區停車場位於觀星草原平台的下方，所以不用擔心車燈光害影響觀星，為我們提供最高品質的星空美景。",
          stargazing_address: "臺東縣東河鄉都蘭61號",
          stargazing_link: "https://goo.gl/maps/vAQroTKdWDKDUjf48",
          stargazing_lid: "1650321467",
          published: true,
          __typename: "Stargazing",
        },
        {
          stargazing_title: "台東：關山親水公園",
          stargazing_latitude: 23.040162889616862,
          stargazing_longitude: 121.17393181278385,
          stargazing_image: "/img/mark-0009.jpg",
          stargazing_description:
            "位於海岸山脈與中央山脈縱谷間的關山親水公園，地理位置清淨優雅，是親子旅遊、戲水與騎單車的好去處，白天能眺望關山鎮無邊際的田園風光，而夜間則能抬頭仰望繁星點點的絕美風景。",
          stargazing_address: "臺東縣關山鎮隆盛路1號",
          stargazing_link: "https://goo.gl/maps/5zguXmXyLv5F89r77",
          stargazing_lid: "1650321466",
          published: true,
          __typename: "Stargazing",
        },
        {
          stargazing_title: "台東：池上大坡池",
          stargazing_latitude: 23.11698444511837,
          stargazing_longitude: 121.22535837679713,
          stargazing_image: "/img/mark-0008.jpg",
          stargazing_description:
            "大坡池白天是花東縱谷知名的景點，不少人會選擇在當地騎單車、賞夏荷、遊竹筏趕送美麗樸素的景色。不過大坡池的夜景也讓人驚艷，天氣好便能看見滿天的星斗倒映於水面中，是賞星必去景點！",
          stargazing_address: "臺東縣池上鄉(臺9線322K東側轉入)",
          stargazing_link: "https://goo.gl/maps/5RwmrGRsVf6rZjx78",
          stargazing_lid: "1650321465",
          published: true,
          __typename: "Stargazing",
        },
        {
          stargazing_title: "蘭嶼：蘭嶼氣象站",
          stargazing_latitude: 22.037406340161123,
          stargazing_longitude: 121.55864597644853,
          stargazing_image: "/img/mark-0007.jpg",
          stargazing_description:
            "蘭嶼有台灣最美小島封號，自然原始，讓這裡成了觀星最美小島！置高點的蘭嶼氣象站，是獨占山景及星空的絕美地方，天氣好時，就像是銀河系覆蓋了整個島嶼，哪怕只是一秒，都讓人美到捨不得眨眼～",
          stargazing_address: "臺東縣蘭嶼鄉紅頭村2號",
          stargazing_link: "https://goo.gl/maps/AwNsdmEfpZYY7mfR7",
          stargazing_lid: "1650321464",
          published: true,
          __typename: "Stargazing",
        },
        {
          stargazing_title: "綠島：帆船鼻大草原",
          stargazing_latitude: 22.636130832588435,
          stargazing_longitude: 121.50827758134503,
          stargazing_image: "/img/mark-0006.jpg",
          stargazing_description:
            "位於台灣本島外的綠島，相較於都市的光害少了許多，尤其是帆船鼻大草原，站在景觀台上擁抱夜空的點點繁星，實在是太幸福啦～",
          stargazing_address: "臺東縣綠島鄉東南角",
          stargazing_link: "https://goo.gl/maps/LWwkBgDfsYTouhmQ7",
          stargazing_lid: "1650321463",
          published: true,
          __typename: "Stargazing",
        },
        {
          stargazing_title: "台東：大武濱海公園",
          stargazing_latitude: 22.359312118429415,
          stargazing_longitude: 120.9075719954937,
          stargazing_image: "/img/mark-0005.jpg",
          stargazing_description:
            "沿著海岸線，可見群星閃爍著，大武濱海公園的星群屬於三等星，雖然沒有一等星的星光閃爍，但可以享受躺在海灘旁細數星星的無敵浪漫！",
          stargazing_address: "臺東縣大武鄉大武濱海公園",
          stargazing_link: "https://goo.gl/maps/Rj48PiCMQMjnBtB8A",
          stargazing_lid: "1650321462",
          published: true,
          __typename: "Stargazing",
        },
        {
          stargazing_title: "台東：長濱金剛大道",
          stargazing_latitude: 23.329304670426,
          stargazing_longitude: 121.44073286111994,
          stargazing_image: "/img/mark-0004.jpg",
          stargazing_description:
            "繁星就像是從銀河偷溜了出來，運氣好時可以在金剛大道觀看銀河橫跨夜空的美，只要仰望臺東的天空，就能看見令人屏息的滿天星斗，讓人讚嘆大自然的不可思議啊～",
          stargazing_address: "臺東縣長濱鄉東13鄉道(長光產業道路)",
          stargazing_link: "https://goo.gl/maps/3vh39x3NH3A6ReeT6",
          stargazing_lid: "1650321461",
          published: true,
          __typename: "Stargazing",
        },
      ],
      pageInfo: {
        hasNextPage: true,
        hasPreviousPage: false,
        start: 1650321470,
        end: 1650321461,
        totalPagi: 2,
        __typename: "PageInfoPush",
      },
      __typename: "StargazingConnectionPush",
    },
  },
};
