name: Deploy to Railway

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '8.15.3'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Check Node, pnpm, Prisma, and TypeScript versions
        run: |
          node -v
          pnpm -v
          pnpm prisma -v
          pnpm tsc -v

      - name: Set up environment variables
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

      - name: ctsb Generate Prisma Client
        run: pnpm exec nx prisma:g cts-back-end

      - name: Build project
        run: pnpm exec nx deploy cts-back-end
        
      - name: Setup Railway CLI
        run: pnpm install -g @railway/cli

      - name: cp dist cts content
        run: |
          ls
          cp docker-compose.yml dist/cts/
          cp .env.production dist/cts/
          cp apps/cts-back-end/deployment/backend/Dockerfile dist/cts/backend/
          mkdir dist/cts/nginx/
          cp apps/cts-back-end/deployment/nginx/nginx.conf dist/cts/nginx/
  
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
            cd dist/cts
            railway link -p "1afbc0b7-f0f1-4067-a841-21709cf628cf"
            railway up --detach


       
