name: Deploy to Railway

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '8.15.3'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Set up environment variables
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env
          
      - name: ctsb Generate Prisma Client
        run: pnpm exec nx prisma:g cts-back-end

      - name: Build ctsb & ctsf project
        run: pnpm exec nx deploy cts-back-end

      - name: cp dist content
        run: |
          cp .env dist/ctsb/          
          cp apps/cts-front-end/deployment/* dist/ctsf/

      - name: Setup Railway CLI
        run: pnpm install -g @railway/cli

      - name: Deploy to Railway (Backend)
        run: |
          cd dist/ctsb
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway up -s ${{ secrets.RAILWAY_SERVICE_CTSB_ID }}

      - name: Deploy to Railway (Frontend)
        run: |
          cd dist/ctsf
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway up -s ${{ secrets.RAILWAY_SERVICE_CTSF_ID }}


       
