name: Deploy Ctsf

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: | 
          pnpm install --no-frozen-lockfile
          pnpm install -g @railway/cli

      - name: Build Frontend
        run: |
          rm -rf dist/ctsf
          mkdir -p dist/ctsf
          
          echo "${{ secrets.ENV_PRODUCTION }}" > .env

          pnpm exec nx build cts-front-end
          cp apps/cts-front-end/deployment/* dist/ctsf/    
          cp .env dist/ctsf/

      - name: Deploy Frontend
        run: |
          cd dist/ctsf
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway up -s ${{ secrets.RAILWAY_SERVICE_CTSF_ID }}
