name: Deploy Ctsb

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: | 
          pnpm install --no-frozen-lockfile
          pnpm install -g @railway/cli

      - name: Build Backend
        run: |
          rm -rf dist/ctsb
          mkdir -p dist/ctsb

          echo "${{ secrets.ENV_PRODUCTION }}" > .env

          pnpm exec nx prisma:g cts-back-end
          pnpm exec nx build cts-back-end
          cp .env dist/ctsb/

      - name: Deploy Backend
        run: |
          cd dist/ctsb
          RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }} railway up -s ${{ secrets.RAILWAY_SERVICE_CTSB_ID }}

